package me.dexrn.jos.common.test.polymorphism;

import java.io.Serializable;

public abstract class JOSPolymorphicBase implements Serializable {
	int i = 0;
	long hfdiukjhsdjfihsdkjihjukosfsfkjhbsjdhkfbsjhknfbhjuisdfbhjksdbfhjkisbdfhjbsdfhjkbsdfhshdjfghjsdfghjsdgfhjgsdhfjgsdhjfgshjdfhfdiukjhsdjfihsdkjihjukosfsfkjhbsjdhkfbsjhknfbhjuisdfbhjksdbfhjkisbdfhjbsdfhjkbsdfhshdjfghjsdfghjsdgfhjgsdhfjgsdhjfgshjdfhfdiukjhsdjfihsdkjihjukosfsfkjhbsjdhkfbsjhknfbhjuisdfbhjksdbfhjkisbdfhjbsdfhjkbsdfhshdjfghjsdfghjsdgfhjgsdhfjgsdhjfgshjdfhfdiukjhsdjfihsdkjihjukosfsfkjhbsjdhkfbsjhknfbhjuisdfbhjksdbfhjkisbdfhjbsdfhjkbsdfhshdjfghjsdfghjsdgfhjgsdhfjgsdhjfgshjdf = 5;
}
